# Generated by Django 2.2.24 on 2021-10-19 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0003_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='total_score',
            field=models.IntegerField(default=1, verbose_name='合計'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='character',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='キャラクター'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='draw',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='画力'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='fit',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='面白さ'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='story',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='内容'),
        ),
    ]
