# Generated by Django 2.2.24 on 2021-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0004_auto_20211019_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='合計'),
        ),
    ]
