# Generated by Django 3.2.7 on 2021-10-21 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0005_auto_20211019_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='character',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='キャラクター'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='draw',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='画力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='fit',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='面白さ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='story',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='合計'),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
