# Generated by Django 3.2.7 on 2021-10-21 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0006_auto_20211021_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='book_name',
            new_name='book_title',
        ),
        migrations.RemoveField(
            model_name='title',
            name='character',
        ),
        migrations.RemoveField(
            model_name='title',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='title',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='title',
            name='story',
        ),
        migrations.RemoveField(
            model_name='title',
            name='total_score',
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='内容')),
                ('draw', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='画力')),
                ('fit', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='面白さ')),
                ('character', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='キャラクター')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='合計')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='comic_app.title', verbose_name='タイトル')),
            ],
        ),
    ]
