# Generated by Django 2.2.24 on 2021-10-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0008_auto_20211025_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='total_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='comic_app.Title', verbose_name='合計'),
        ),
    ]
